### ISSUE TITLE
timeout option is not working in sample producer

### ISSUE THREAD

**Issue by davidor** [awslabs/amazon-kinesis-client-ruby#11]
The sample producer crashes when the timeout option is used.

This is the error I get: sample_kcl_producer.rb:124:in `block (2 levels) in <main>': undefined local variable or method`s' for main:Object (NameError).

**Comment by Cory-Bradshaw** [comment]
Thank you for reporting this issue. If this is still ongoing for other customers, please +1 this issue and we can work on prioritizing this fix.
