### ISSUE TITLE
Struggling to get example consumer working

### ISSUE THREAD

**Issue by verenion** [awslabs/amazon-kinesis-client-ruby#24]
I've been trying to get the example consumer working correctly our multiple AWS accounts. I've tried with both the Node.JS client and now the ruby client, both throw the same error after a few minutes:

```SEVERE: Failed to get status message for initialize action for shard shardId-000000000000
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Reached end of STDIN of child process for shard shardId-000000000000 so won't be able to return a message.
```

This is the default code and nothing has been changed but the connection/stream details. Anyone else having issues getting the samples to run?

**Comment by pfifer** [comment]
I'll take a look, and see make sure that it's working.  I do have some questions that could help me in troubleshooting this:
* Where are you trying to run the sample applications (EC2, Laptop/Desktop, Elsewhere)
* What OS are you trying to run the sample on?

**Comment by verenion** [comment]
Thanks, we managed to resolve this issue. Turned out to be an error our end. It was becuase of where we were running the script from. We ended up fixing our node client, so rather than `bin/kcl-bootstrap`, we used `../bin/kcl-bootstrap`. In the ruby client, it was because it couldn't find the `kclrb.rb` file. In both cases, the client process was throwing errors, but not showing them in the logs.
