### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by mallyvai** [awslabs/amazon-kinesis-client-ruby#25]
PRs are not being responded to, and there have not been any updates in 8 months. If we are evaluating streaming solutions for our Ruby/Rails application is it fair to take this as a negative signal?

**Comment by Cory-Bradshaw** [comment]
No, this is not abandonware, we apologize for giving that impression, as our focus recently has been on the Java KCL.  We plan to have a more streamlined release process going forward, including updates to the Multi-Lang daemons as features and fixes become available on the Java KCL.
