### ISSUE TITLE
GracefulShutdown fails

### ISSUE THREAD

**Issue by aelaa** [awslabs/amazon-kinesis-client-ruby#36]
Tried to run on both my application and sample from this repo. Every time I'm trying to stop the application, I see next message:
```
2019-04-04 10:36:23,894 [RequestedShutdownThread] INFO  s.a.k.c.GracefulShutdownCoordinator$GracefulShutdownCallable [NONE] - Shutdown completed, but shutdownCompleteLatch still had outstanding 2 with a current value of 2. shutdownComplete: false -- Consumer Map: 0
```
I suppose application's stopping properly, but KCL still waits for something. Is it OK?

**Comment by Cory-Bradshaw** [comment]
Graceful shutdowns attempts allowing the running record processors to finish the work they are doing. If the consumers are particularly long running you may need to force the shutdown non-gracefully. 

This message is saying that there were 2 consumers running, and 2 that are still running. The shutdown did not complete. You can either try calling the graceful shutdown again and await the consumers to finish their work, or you can more forcibly shutdown the worker.

Per our docs:

https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-implementation-app-java.html
````
If the shutdown reason is TERMINATE, the record processor should finish processing 
any data records, and then call the checkpoint method on this interface.
````

If you continue to experience problems with shutting down a KCL worker, you can open an AWS Support case in the AWS Console to provide more information around configuration, use case, and the code you are using and we can try our best to help troubleshoot the problems you are seeing.
