### ISSUE TITLE
example does not work in eu-central-1

### ISSUE THREAD

**Issue by yannick** [awslabs/amazon-kinesis-client-ruby#4]
if i change region to eu-central-1  i get 

```
 Stream testme under account XXX not found. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 5cd33d33-f1cb-11e4-9fa7-e5838a497e54)
```

even though this stream in frankfurt exists. everything works fine if i use eu-west-1
might be a bug in amazon-kinesis-client

**Comment by jqr** [comment]
Are you changing the `regionName` in [sample.properties](https://github.com/awslabs/amazon-kinesis-client-ruby/blob/master/samples/sample.properties#L32)?

**Comment by yannick** [comment]
yes. is there another way?

seems to be related to the sdk version? 
https://github.com/awslabs/amazon-kinesis-client-python/issues/4

**Comment by kevincdeng** [comment]
Hey guys,

This is indeed the same problem as that in the python KCL issue linked above. The same workaround should work. We are working on an updated release that fixes this problem.

**Comment by Cory-Bradshaw** [comment]
Closing this issue, as more recent releases have updated the AWS SDK to a version that supports this region.
