### ISSUE TITLE
How does one opt-out of enhanced fan out?

### ISSUE THREAD

**Issue by webandtech** [awslabs/amazon-kinesis-client-ruby#40]
I scanned the example properties file and it didn't seem clear... if I want to use this with the old GetRecords behavior instead of SubscribeToShard, how does one configure the kcl to do that?

**Comment by jl-gogovapps** [comment]
@webandtech , I had the same question this morning and found my way to this answer:
https://github.com/awslabs/amazon-kinesis-client/issues/429#issuecomment-500251216

**Comment by cbatson** [comment]
In `consumer.properties` set

```
# Set to POLLING to disable enhanced fan-out mode
retrievalMode=POLLING
```
