### ISSUE TITLE
Upgrade Kinesis client

### ISSUE THREAD

**Issue by Bottelet** [awslabs/amazon-kinesis-client-ruby#41]
Are there any plans for upgrading the core kinesis library version to the latest? 

We are looking to use `idleTimeBetweenReadsInMillis,` but it seems it is ignored till version [2.3.3](https://github.com/awslabs/amazon-kinesis-client#release-233-december-23-2020)

**Comment by brendan-p-lynch** [comment]
It has been upgraded to 2.4.4: https://github.com/awslabs/amazon-kinesis-client-ruby/blob/v2.1.1/pom.xml#L16
