### ISSUE TITLE
run producer doesn't work

### ISSUE THREAD

**Issue by ghost** [awslabs/amazon-kinesis-client-ruby#7]
when i run rake run_producer I get

``` bash
..
.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- aws/kinesis (LoadError)
    from /Users/asdf/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/asdf/workspace/expeditions/amazon-kinesis-client-ruby/samples/sample_kcl_producer.rb:16:in `<main>'
```

do note, instead of installign via

``` bash
sudo gem install aws-sdk
```

I am using RVM and I did a 

``` bash
gem install aws-sdk
```

**Comment by pacuna** [comment]
I had this same issue. What I did was:

- Install the aws-sdk-core gem
- add require 'aws-sdk-core' to the sample_kcl_producer.rb file and remove the call to aws/kinesis
- replace all the calls to AWS::Kinesis with Aws::Kinesis

**Comment by aw2611** [comment]
Ran into the same problem, and @pacuna workaround worked for me.
Thanks :+1:

**Comment by Cory-Bradshaw** [comment]
Thank you for raiseing this issue and providing details. We can look into this issue during our next release, as we start releasing and updating the multilang libraries more regularly.

**Comment by lucienlu-aws** [comment]
should be fixed in recent PR
