### ISSUE TITLE
Supported Native Ruby KCLRB

### ISSUE THREAD

**Issue by witoff** [awslabs/amazon-kinesis-client-ruby#8]
howdy all, we love the idea of using kclrb but this unsupported java/ruby frankenstein is becoming quite painful for us.  there hasn't been a meaningful commit here in nearly a year, there are no tests, new kinesis features are not available and the java code cannot be easily instrumented, monitored or updated.  if anyone is inclined to publish a fault tolerant, distributed at-least once processing library natively in ruby we will happily support the development of this.  please get in touch directly if interested.

**Comment by rzfoxify** [comment]
Hi! Did you have any progress in this field or still want to?

**Comment by Cory-Bradshaw** [comment]
Closing this issue in favor of #27 .

Please +1 that issue and provide details of what problems you are facing with the multilang library and how we can make this more seamless for your usecases.
